---
title: |
       | Main Title
       | Sub Title

author: |
        | Dr.-Ing. Raul Trujillo Alvarez
        | co-author

date: '`r Sys.Date()`'

output:
  pdf_document:
    fig_caption: true
    fig_width: 7
    fig_height: 6
    highlight: tango
    number_sections: true
    toc: true
    toc_depth: 2

fontsize: 11pt
documentclass: article
classoption: oneside
---

# Introduction
This report outlines the findings of [provide description of data analysis] data analysis that has been performed as part of the [name of response] response.

The point of this document is to capture our understanding of the requirements, and how we plan to address them.

This document is used to capture the agreement between we and our customer of what will be built. It is also intended to be a useful reference for your project team.

Not all of the following sections will be relevant for every project. For example, not every project will have a user interface, or a database.

## Background

Briefly give enough background so that a person outside your team reading this document would understand why this document exists and what it is used for.

## Purpose of the analysis
[Describe why the analysis has been undertaken.  It may be regular data analysis for the response or ad-hoc data analysis for a specific purpose.]

## Hypothesis
[If relevant, describe the hypothesis to be tested.]

## Key documents
[List key documents and reports related to this response.]

# Analysis

## Methods
[Describe the methods used: data source/date, assessment of data quality (e.g. missing values, outliers and correlations in these), analysis approach and methodology.]

## Requirements

A numbered list of the main requirements for this project with a brief definition of each requirement (often a sentence will suffice, no more than a short paragraph).  Requirements should be grouped so that similar requirements are grouped together.  The point of this section is to list and identify requirements.  It is not necessary to include a myriad of details that may evolve over time, as long as the main requirement has been identified.

## Example Data and Test Cases

Identify the data that the customer will be providing, or you will be building to test and verify the system throughout the project lifecycle. If it is not currently available, identify the process and schedule by which it will be made available (and highlight it as a risk in your project status report that needs to be managed).  

Please note that you and your customer cannot have possibly come to a common understanding of the requirements, unless you have agreed upon the test cases and sample data that will be used to verify requirements have been met.  It is essential that you start building up these test cases and sample data early.

Identify two or three critical scenarios and define example data for them that will be used to start work on test cases.  You do not have to provide test cases in this document, but you should use the scenarios and example data to illustrate your analysis of the requirements throughout this document.

## Use Case Model or Functional Features of System

Define WHAT functionality the system will provide. Ideally this would be organized around the major use cases the system would support. This can also be organized around the major functions or features of the system. In either case, your system should have somewhere in the range of 3-10 of these use cases or major features. Include an updated use case diagram.

For each use case or feature:

- Identify the requirements that are addressed by it, the actors it is relevant to, and any preconditions or restrictions.

- Define clearly the "normal" flow of interactions with the system. Identify the variations on this normal flow that are possible, and in particular what "exceptions" must be handled.

- Illustrate the normal flow (and variations) with an example using the sample data from one or more of your critical scenarios. (If the illustration will be shown in your user interface mockups, simply reference which screen shot should be looked at)

## Non-Functional Features

Some requirements are non-functional. E.g. the system must be scalable and support a 24*7 usage. Or the system must be usable by novice users. For each of these, describe your strategy for addressing them:

- from a design point of view (how do you plan to design and build the system to address the requirement) and

- from a testing point of view (how do you plan to verify that the requirement is met).

## High Level Architecture

Draw a package diagram (or possibly an updated deployment diagram) that shows the key components of your system (e.g. web server, database, user interface) and what third party technologies you will use or be dependent on (e.g. IIS, MySql, PHP etc.). For each component there should be a brief statement of what its role is in supporting the requirements of the system. Illustrate your architecture by drawing two or three high level interaction diagrams that show how the components interact for your critical scenarios and example data. (If you are using a UML tool like Rational Rose you will need to create a facade class to represent each of your components).

## User Interface Mockup

Screen shots or actual GUI or HTML pages that illustrate the look and feel of the user interface for your critical scenarios. Make sure you use your example data.

## Database Schemas and File Formats

If your data will be stored persistently either in a database or a file, define the relevant database schemas or file formats. Illustrate by showing how your example data will be stored.

## Algorithms

If your system will be dependent on any significant algorithms (pattern recognition, image processing, game strategy, matching problem etc.) then identify them here. Briefly outline the problem that needs to be solved, the alternatives considered, and the algorithm selected. Illustrate the algorithm with an example using the example data.

# Results
[Complete the heading below and/or provide other headings relevant to the purpose of the data analysis.]

## Quality of data
[Describe the quality of the data used in the analysis.  Were there any issues with it that should be taken into consideration when looking at the findings?]

## Other
[Report other finding of the data analysis, as required.]

# Discussion
Summarise findings outlined in subheadings above, focussing on:
- data quality and the effect this may have on drawing conclusions
- spread
- response effectiveness and efficiency and estimates of undetected spread
- predictions.
Discuss the implications of findings for the response effort and the need for further resource.

# Recommendations
[Summarise recommended actions for the response team arising out of the analysis.]
